name: example_file_upload
description: Sample project - designed to be a small taste of Angel.
version: 1.0.0
author: Tobe O
homepage: https://medium.com/@thosakwe/building-a-simple-file-upload-app-with-angel-64938d4ddc61
publish_to: none
dependencies:
  angel_auth: ^1.0.0-dev
  angel_configuration: ^1.0.0-dev
  angel_diagnostics: ^1.0.0-dev
  angel_framework: ^1.0.0-dev
  angel_mongo: ^1.0.0-dev
  angel_mustache: ^1.0.0-dev
  angel_static: ^1.0.0
  json_god: ^2.0.0-beta
  mailer: ^1.1.0+4
  validate: ^1.5.2
dev_dependencies:
  http: ^0.11.3
  grinder: ^0.8.0+2
  test: ^0.12.13
transformers:
- angel_configuration
